# Script to generate the plots for the paper.

# SET UP ENVIRONMENT
# ------------------
library(ggplot2)
library(cowplot)

# Colors used in the plots below.
colors <- c("#E69F00","#56B4E9","#009E73","#F0E442",
            "#0072B2","#D55E00","#CC79A7")

# LOAD RESULTS
# ------------
# Load the results generated by Youngseok.
load("../output/results_for_plots.RData")

# CREATE PLOTS
# ------------
# Create a plot comparing the computation time for solving three
# different formulations of the maximum-likelihood estimation problem
# with MOSEK (in JuMP): (1) the dual problem, (2) the primal problem
# with simple constraints, and (3) the primal problem with
# non-negativity constraints.
p1 <- ggplot(data = dat1_1[-1,]) +
  geom_line(aes(x = n,y = t2,color = "dual"),size = 1) +
  geom_line(aes(x = n,y = t1,color = "primal, simplex-constrained"),size = 1) +
  geom_line(aes(x = n,y = t3,color = "primal, non-negative-constrained"),
            size = 1) +
  geom_point(aes(x = n,y = t2,color = "dual"),size = 3,shape = 20) +
  geom_point(aes(x = n,y = t1,color = "primal, simplex-constrained"),
             size = 3,shape = 20) +
  geom_point(aes(x = n,y = t3,color = "primal, non-negative-constrained"),
             size = 3,shape = 20) +
  scale_x_continuous(trans = "log10",breaks = c(40,100,1e3,1e4)) +
  scale_y_continuous(trans = "log10",breaks = c(0.01,0.1,1,10,100)) + 
  scale_color_manual(values = colors,name = "") +
  labs(x     = "number of data matrix rows (n)",
       y     = "computation time (seconds)",
       title = "MOSEK with different problem formulations") +
  theme_cowplot(font_size = 12) +
  theme(legend.position = c(0.05,0.9),
        plot.title = element_text(face = "plain",size = 12),
        axis.line = element_blank())

# TO DO: Revise this figure.
p2 <- ggplot(data = dat1_2[2:10,]) +
  geom_line(aes(x = log2(n), y=log2(t1),color = "S: simplex"), size = 1.2) +
  geom_line(aes(x = log2(n), y=log2(t2),color = "D: dual"), size = 1.2) +
  geom_line(aes(x = log2(n), y=log2(t3),color = "B: box"), size = 1.2) +
xlab("log2(n)") + ylab("log2(time)") +
scale_color_discrete(name = "") +
    ggtitle("formulation-SQP-O-F with m = 40")  +
  theme(legend.position = c(0.05,0.9))

# TO DO: Briefly explain what these lines of code do.
levels(dat6_1$label) <-
  c("posterior calculations","model fitting (mix-SQP)",
    "QR factorization","likelihood computation")
levels(dat6_2$label) <-
  c("posterior calculations","model fitting (REBayes/MOSEK)",
    "likelihood computation")
dat6_1 <- transform(dat6_1,
                    label = factor(as.character(label),
                      c("QR factorization",
                        "model fitting (mix-SQP)",
                        "posterior calculations",
                        "likelihood computation")))
pdat <- rbind(transform(dat6_1,
                        x     = x - 5e3,
                        label = as.character(label)),
              transform(dat6_2,
                        x     = as.numeric(as.character(x)) + 5e3,
                        label = as.character(label)))
pdat <- transform(pdat,
          label = factor(label,c("QR factorization",
                                 "model fitting (REBayes/MOSEK)",
                                 "model fitting (mix-SQP)",
                                 "posterior calculations",
                                 "likelihood computation")))

# TO DO: Briefly describe here what is being shown in this figure.
p3 <- ggplot(pdat,aes(x = x,y = y,fill = label)) +
  geom_col(position = "stack",width = 7e3) +
    scale_fill_manual(name = "",
      values = c("lightskyblue","orange","orangered","aliceblue",
                 "lightsteelblue")) +
  scale_x_continuous(breaks = seq(5e4,25e4,5e4)) +
  labs(x = "number of data matrix rows (n)",
       y = "computation time (seconds)",
       title = "computation breakdown in adaptive shrinkage") +
  theme_cowplot(font_size = 12) +
  theme(legend.position = c(.05,0.85),
        plot.title = element_text(face = "plain",size = 12),
        axis.line = element_blank(),
        axis.ticks.x = element_blank())

# TO DO: Briefly describe here what is being shown in this figure.
p4 <- ggplot(dat6_1,aes(x = x,y = y,fill = label)) +
  geom_col(position = "stack",width = 7e3) +
    scale_fill_manual(name = "",
      values = c("lightskyblue","orangered","aliceblue","lightsteelblue")) +
  scale_x_continuous(breaks = seq(5e4,25e4,5e4)) +
  labs(x = "number of data matrix rows (n)",
       y = "computation time (seconds)",
       title = "adaptive shrinkage (mix-SQP only)") +
  theme_cowplot(font_size = 12) +
  theme(legend.position = c(.05,0.9),
        plot.title = element_text(face = "plain",size = 12),
        axis.line = element_blank(),
        axis.ticks.x = element_blank())

# SAVE PLOTS AS PDFs
# ------------------
ggsave("../output/F1.pdf",plot_grid(p1,p2),height = 4,width = 8)
ggsave("../output/F6.pdf",plot_grid(p3,p4),height = 4,width = 8)

stop()

## figure 2

p <- ggplot(data = dat2_1) +
  geom_line(aes(x = log2(n), y=log2(t1),color = "F"), size = 1.2) +
  geom_line(aes(x = log2(n), y=log2(t2),color = "SVD"), size = 1.2) +
  geom_line(aes(x = log2(n), y=log2(t3),color = "QR"), size = 1.2)
p <- p + xlab("log2(n)") + ylab("log2(time)")
p1 <- p + scale_color_discrete(name = "") + ggtitle("B-SQP-A-lowrankapprox")  +
  theme(legend.position = c(.1,.9))

p <- ggplot(data = dat2_2) +
  geom_line(aes(x = log2(n), y=svd,color = "SVD"), size = 1.2) +
  geom_line(aes(x = log2(n), y=qr,color = "QR"), size = 1.2)
p <- p + xlab("log2(n)") + ylab("log10(frobenius error)")
p2 <- p + scale_color_discrete(name = "") +
    ggtitle("accuracy of low-rank approximation") + ylim(c(-13,-12))  +
  theme(legend.position = c(.1,.9))
multiplot(p1, p2, cols = 2)

## figure 3

p <- ggplot(data = dat3_1) +
  geom_line(aes(x = log2(m), y= log2(s/m),color = "synthetic"), size = 1.2) +
  geom_line(aes(x = log2(m2), y = log2(s2/m),color = "GIANT"), size = 1.2)
p <- p + xlab("log2(m)") + ylab("log2(r/m)")
p <- p + scale_color_discrete(name = "") + ggtitle("log2(rank/m)") +
  theme(legend.position = c(.8,.95),legend.background = element_rect(fill = "transparent"))
p2 <- ggplot(data = dat3_2) + geom_line(aes(x = log2(m), y = rel_err),color = "#00BA38", size = 1.2)
p3 <- ggplot(data = dat3_3) + geom_line(aes(x = log2(m), y = rel_err ),color = "#619CFF", size = 1.2)
p2 <- p2 + xlab("log2(m)") + ylab("log10(||x_IP - x_SQP||_1)") + ggtitle("difference in l1 norm") + ylim(-8,-4)
p3 <- p3 + xlab("log2(m)") + ylab("log10(|f_IP-f_SQP|/|f_IP|)") + ggtitle("difference in objective") + ylim(-16,-8)
multiplot(p, p2, p3, cols=3)

## figure 4

p <- ggplot(data = dat4_1) +
  geom_line(aes(x = log2(m), y=log2(t1),color = "IP"), size = 1.2) +
  geom_line(aes(x = log2(m), y=log2(t2),color = "Act"), size = 1.2)
p <- p + xlab("log2(m)") + ylab("log2(time)")
p1 <- p + scale_color_discrete(name = "") + ggtitle("comptime of solving QP in m")  +
  theme(legend.position = c(.1,.95),legend.background = element_rect(fill = "transparent"))

p <- ggplot(data = dat4_2) +
  geom_line(aes(x = log2(n), y=log2(t1),color = "IP"), size = 1.2) +
  geom_line(aes(x = log2(n), y=log2(t2),color = "Act"), size = 1.2)
p <- p + xlab("log2(n)") + ylab("log2(time)")
p2 <- p + scale_color_discrete(name = "") + ggtitle("comptime of solving QP in n")  +
  theme(legend.position = c(.9,.6),legend.background = element_rect(fill = "transparent"))

p <- ggplot() +
  geom_line(aes(x = 1:17, y=dat4_3$q_nnz,color = "q_nnzs"), size = 1.2) +
  geom_line(aes(x = 1:17, y=dat4_3$y_nnz,color = "y_nnzs"), size = 1.2) +
  geom_line(aes(x = 1:17, y=dat4_3$linesearch,color = "# of ls"), size = 1.2) 
p <- p + xlab("iteration") + ylab("number")
p3 <- p + scale_color_discrete(name = "") + ggtitle("parameters in each iteration")  +
  theme(legend.position = c(.9,.9),legend.background = element_rect(fill = "transparent"))
multiplot(p1, p2, p3, cols = 3)


## figure 5

p <- ggplot(data = dat5) +
  geom_line(aes(x = n, y=log2(IP100),color = "pink",linetype = "D-IP-N-F"), size = 1.2) +
  geom_line(aes(x = n, y=log2(SQP100),color = "pink",linetype = "B-SQP-A-QR"), size = 1.2) + 
  geom_line(aes(x = n, y=log2(IP200),color = "turquoise",linetype = "D-IP-N-F"), size = 1.2) +
  geom_line(aes(x = n, y=log2(SQP200),color = "turquoise",linetype = "B-SQP-A-QR"), size = 1.2) +
  geom_line(aes(x = n, y=log2(IP400),color = "blue",linetype = "D-IP-N-F"), size = 1.2) +
  geom_line(aes(x = n, y=log2(SQP400),color = "blue",linetype = "B-SQP-A-QR"), size = 1.2) +
  geom_line(aes(x = n, y=log2(IP800),color = "salmon",linetype = "D-IP-N-F"), size = 1.2) +
  geom_line(aes(x = n, y=log2(SQP800),color = "salmon",linetype = "B-SQP-A-QR"), size = 1.2)
p1 <- p + xlab("log2(n)") + ylab("log2(time)")
fig5 <- p1 + scale_color_discrete(name = "m", breaks = c("pink","blue","turquoise","salmon"),
                                  labels = c("100", "200","400","800")) + ggtitle("Computation time of mixSQP versus REBayes")+
  theme(legend.position = c(.1,.75),legend.background = element_rect(fill = "transparent"))
fig5

