# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mixsqp_rcpp <- function(L, x0, convtol, eps, maxiter, verbose) {
    .Call('_mixopt_mixsqp_rcpp', PACKAGE = 'mixopt', L, x0, convtol, eps, maxiter, verbose)
}

